name: Metrics
on:
  # 매일 자정 자동 업데이트
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: letminjae
          template: classic
          base: ""
          
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, json, yaml, xml
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes

          repositories_batch: 200
          plugin_languages_limit: 8

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 30
          plugin_activity_filter: push, issue, pr
          plugin_activity_visibility: all

          plugin_recent_posts: yes
          plugin_recent_posts_source: github
          plugin_recent_posts: 4

          config_timezone: Asia/Seoul
          theme: radical
