name: Stable Metrics
on:
  # 매일 자정 자동 업데이트
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: letminjae
          template: classic
          base: ""

          # 최근 언어 활동만 활성화
          plugin_activity: yes
          plugin_activity_limit: 3
          plugin_activity_days: 1
          plugin_activity_visibility: public

          config_timezone: Asia/Seoul
          theme: radical
